# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/shell_sage',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/shell_sage',
                'lib_path': 'shell_sage'},
  'syms': { 'shell_sage.core': { 'shell_sage.core.get_history': ('core.html#get_history', 'shell_sage/core.py'),
                                 'shell_sage.core.main': ('core.html#main', 'shell_sage/core.py'),
                                 'shell_sage.core.run_cmd': ('core.html#run_cmd', 'shell_sage/core.py')}}}
