# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/shell_sage',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/shell_sage',
                'lib_path': 'shell_sage'},
  'syms': { 'shell_sage.config': { 'shell_sage.config.ShellSageConfig': ('config.html#shellsageconfig', 'shell_sage/config.py'),
                                   'shell_sage.config._cfg_path': ('config.html#_cfg_path', 'shell_sage/config.py'),
                                   'shell_sage.config.get_cfg': ('config.html#get_cfg', 'shell_sage/config.py')},
            'shell_sage.core': { 'shell_sage.core._aliases': ('core.html#_aliases', 'shell_sage/core.py'),
                                 'shell_sage.core._sys_info': ('core.html#_sys_info', 'shell_sage/core.py'),
                                 'shell_sage.core.get_history': ('core.html#get_history', 'shell_sage/core.py'),
                                 'shell_sage.core.get_opts': ('core.html#get_opts', 'shell_sage/core.py'),
                                 'shell_sage.core.get_pane': ('core.html#get_pane', 'shell_sage/core.py'),
                                 'shell_sage.core.get_panes': ('core.html#get_panes', 'shell_sage/core.py'),
                                 'shell_sage.core.get_sage': ('core.html#get_sage', 'shell_sage/core.py'),
                                 'shell_sage.core.main': ('core.html#main', 'shell_sage/core.py'),
                                 'shell_sage.core.tmux_history_lim': ('core.html#tmux_history_lim', 'shell_sage/core.py')}}}
