# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/bash_buddy',
                'doc_host': 'https://AnswerDotAI.github.io',
                'git_url': 'https://github.com/AnswerDotAI/bash_buddy',
                'lib_path': 'bash_buddy'},
  'syms': {'bash_buddy.core': {'bash_buddy.core.foo': ('core.html#foo', 'bash_buddy/core.py')}}}
